name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        ruby:buster /bin/bash -c "chmod -R 777 /srv/jekyll && cd /srv/jekyll && bundler install && bundler exec jekyll build --future"
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ${{ github.workspace }}/_site # The folder the action should deploy.
